---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: worker-example
  namespace: test
  generateName: vs-worker-
  labels:
    machine.uccp.io/cluster-api-cluster: tb-asg-35
    machine.uccp.io/cluster-api-machine-role: infra
    machine.uccp.io/cluster-api-machine-type: worker
spec:
  providerSpec:
    value:
      apiVersion: libvirtproviderconfig.k8s.io/v1alpha1
      kind: LibvirtMachineProviderConfig
      domainMemory: 2048
      domainVcpu: 2
      cloudInit:
        sshAccess: true
        userDataSecret: libvirt-actuator-user-data-secret
      volume:
        poolName: default
        baseVolumeID: fedora_base
      networkInterfaceName: default
      networkInterfaceAddress: 192.168.122.0/24
      autostart: false
      uri: qemu+ssh://root@147.75.96.109/system
  versions:
    kubelet: ""
    controlPlane: ""
